--- # This is a basic workflow to help you get started with Actions

name: List supported

on:
  push:
    paths:
      - 'quickget'
    branches: ['**'] #'!master' # excludes master
  pull_request:
    branches: ['**'] # matches every branch

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  list-supported:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Prerequisites
        run: |
          echo "               Supported:"
          ./quickget -ls > supported.list

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Supported OS with releases and editions
          path: |
            supported.list

  list-ISOs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Prerequisites
        run: |
          echo "               ISOs:"
          ./quickget -li > ISOs.list

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Supported OS with releases and editions
          path: |
            ISOs.list
